name: Python GCP Storage

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: execute py script
      env:
        GCP_CREDENCIALS: ${{ secrets.GCP_CREDENCIALS }}
      run: 
        python python_names_storage.py
      